=== uo264691/SEW2024/F1Desktop/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="circuito">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>

        <xs:element name="longitud_circuito">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:float">
                <xs:attribute name="unidad" type="xs:string" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>

        <xs:element name="anchura_media">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:float">
                <xs:attribute name="unidad" type="xs:string" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>

        <xs:element name="fecha_carrera" type="xs:date"/>
        <xs:element name="hora_inicio" type="xs:time"/>

        <xs:element name="vueltas">
          <xs:simpleType>
            <xs:restriction base="xs:positiveInteger">
              <xs:minInclusive value="1"/>
              <xs:maxInclusive value="200"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>

        <xs:element name="localidad" type="xs:string"/>
        <xs:element name="pais" type="xs:string"/>

        <xs:element name="referencias">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="referencia" type="xs:anyURI" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="galeria_fotografias">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="fotografia" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="galeria_videos" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="video" type="xs:string" maxOccurs="unbounded"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="coordenadas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="longitud_geo" type="xs:float"/>
              <xs:element name="latitud_geo" type="xs:float"/>
              <xs:element name="altitud">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:float">
                      <xs:attribute name="unidad" type="xs:string" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="tramos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="tramo" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="longitud_geo" type="xs:float"/>
                    <xs:element name="latitud_geo" type="xs:float"/>
                    <xs:element name="altitud">
                      <xs:complexType>
                        <xs:simpleContent>
                          <xs:extension base="xs:float">
                            <xs:attribute name="unidad" type="xs:string" use="required"/>
                          </xs:extension>
                        </xs:simpleContent>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="sector" type="xs:positiveInteger"/>
                  </xs:sequence>
                  <xs:attribute name="distancia" type="xs:float" use="required"/>
                  <xs:attribute name="unidad" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== uo264691/SEW2024/F1Desktop/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="circuito.xsd">
    <nombre>Autódromo Hermanos Rodríguez</nombre>
    <longitud_circuito unidad="km">4.304</longitud_circuito>
    <anchura_media unidad="m">15</anchura_media>
    <fecha_carrera>2024-10-27</fecha_carrera>
    <hora_inicio>14:00:00</hora_inicio>
    <vueltas>71</vueltas>
    <localidad>Ciudad de México</localidad>
    <pais>México</pais>
    <referencias>
        <referencia>https://es.wikipedia.org/wiki/Aut%C3%B3dromo_Hermanos_Rodr%C3%ADguez</referencia>
        <referencia>https://www.formula1.com/en/racing/2024/Mexico.html</referencia>
        <referencia>https://www.sportingnews.com/es/formula-1/news/autodromo-hermanos-rodriguez-nombre-circuito-gran-premio-mexico/jhcklw99g8kuzl5ygn5ot1a4</referencia>
    </referencias>
    <galeria_fotografias>
        <fotografia>circuito.png</fotografia>
        <fotografia>actualidad.jpg</fotografia>
        <fotografia>hermanos.webp</fotografia>
    </galeria_fotografias>
    <galeria_videos>
        <video>max-verstappen-s-onboard-pole-lap-2022-mexico-city-grand-prix.mp4</video>
    </galeria_videos>
    <coordenadas>
        <longitud_geo>-99.093072</longitud_geo>
        <latitud_geo>19.404167</latitud_geo>
        <altitud unidad="m">2240</altitud>
    </coordenadas>
    <tramos>
    <tramo distancia="136.69" unidad="m">
        <longitud_geo>-99.09000</longitud_geo>
        <latitud_geo>19.40167</latitud_geo>
        <altitud unidad="m">2240</altitud>
        <sector>1</sector>
    </tramo>
    <tramo distancia="157.12" unidad="m">
        <longitud_geo>-99.09056</longitud_geo>
        <latitud_geo>19.40278</latitud_geo>
        <altitud unidad="m">2240</altitud>
        <sector>2</sector>
    </tramo>
    <tramo distancia="412.70" unidad="m">
        <longitud_geo>-99.09194</longitud_geo>
        <latitud_geo>19.40333</latitud_geo>
        <altitud unidad="m">2240</altitud>
        <sector>3</sector>
    </tramo>
    <tramo distancia="412.70" unidad="m">
        <longitud_geo>-99.09583</longitud_geo>
        <latitud_geo>19.40389</latitud_geo>
        <altitud unidad="m">2240</altitud>
        <sector>4</sector>
    </tramo>
</tramos>
</circuito>
